name: Spell Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: zwaldowski/cspell-action@1.0.0
        with:
          paths: "**/*.{md,js,vue}"
          unique: true 
